export const img = (id, w = 900) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=70`

// Puestos de docs/puestos (Departamento de Redes); documentos pre-renderizados en public/puestos (npm run puestos)
export const PUESTOS = [
  {
    clave: 'coordinador', codigo: 'TIC-RED-001', denominacion: 'Scrum Master / Coordinador de Redes', categoria: 'Directivo', color: 'yellow', icon: '◎',
    // integrante y perfil MBTI ilustrativos (página MBTI)
    person: 'Andrés León', mbti: 'ENFJ', alias: 'El Protagonista',
    perfil: 'Líder cercano que alinea al equipo en torno a objetivos claros. Detecta tensiones antes de que escalen y convierte los impedimentos en acuerdos concretos.',
    fortalezas: ['Facilita reuniones productivas', 'Motiva y da visibilidad al trabajo del equipo', 'Media entre áreas técnicas y la dirección'],
    retos: ['Puede asumir demasiados compromisos', 'Le cuesta dar feedback negativo directo'],
    comunicacion: 'Háblale del impacto en el equipo y en el cliente; valora las conversaciones cara a cara.',
    subtitulo: 'Coordinación y facilitación ágil del área de Redes', nivel: 'Nivel 2 · Coordinación', reportaA: 'Dirección de Tecnología y Producto',
    supervisa: ['Administrador de Redes', 'Especialista en Seguridad de Redes', 'Soporte y Monitoreo de Redes'],
    funcionales: 'Coordina con Infraestructura, Desarrollo y proveedores de servicios de telecomunicaciones.',
    proposito: 'Dirigir la operación integral de la red corporativa y facilitar Scrum en el equipo de Redes, garantizando disponibilidad, seguridad y entrega continua de valor.',
    funciones: ['Definir y supervisar el plan de trabajo, la arquitectura y las políticas de la red corporativa.', 'Facilitar las ceremonias Scrum: planificación de sprint, reunión diaria, revisión y retrospectiva.', 'Coordinar al equipo técnico —administración, seguridad y soporte— en sus objetivos específicos.', 'Identificar y remover impedimentos que bloqueen el avance del equipo.', 'Analizar reportes de disponibilidad, tráfico e incidentes y proponer mejoras.', 'Tomar decisiones ante imprevistos, contingencias o incidentes críticos.', 'Representar al área de Redes ante la dirección y las demás jefaturas de Tecnología.'],
    responsabilidades: ['Presupuesto y recursos tecnológicos asignados al área.', 'Seguridad y confidencialidad de la información que circula por la red.', 'Decisiones críticas que afectan la disponibilidad de los servicios.', 'Desarrollo profesional, evaluación y clima laboral del equipo.'],
    autoridad: ['Aprobar cambios de configuración de alto impacto.', 'Asignar prioridades del backlog técnico junto al Product Owner.', 'Autorizar ventanas de mantenimiento y guardias.'],
    requisitos: ['Ingeniería en Sistemas, Informática, Telecomunicaciones o afines.', 'Mínimo 5 años gestionando equipos e infraestructura de red.', 'Certificación Scrum (PSM, CSM o equivalente).', 'Conocimientos avanzados de LAN/WAN, enrutamiento y conmutación.'],
    competencias: ['Liderazgo de equipos de alto desempeño', 'Orientación a resultados', 'Facilitación y negociación', 'Pensamiento estratégico', 'Mejora continua'],
    indicadores: [['Disponibilidad de la red', '≥ 99.9 % mensual'], ['Cumplimiento de objetivos de sprint', '≥ 85 %'], ['Ejecución presupuestaria', '± 5 % de lo planificado'], ['Retrospectivas con acciones cerradas', '100 %']],
    condiciones: ['Oficina con posibilidad de trabajo remoto.', 'Disponibilidad para emergencias fuera de horario.', 'Visitas ocasionales a sedes y centros de datos.'],
    riesgos: ['Estrés por incidentes críticos en tiempo reducido.', 'Sobrecarga en picos de demanda o mantenimientos.'],
  },
  {
    clave: 'administrador', codigo: 'TIC-RED-002', denominacion: 'Administrador de Redes', categoria: 'Profesional / Técnico especializado', color: 'blue', icon: '⇄',
    person: 'Sofía Vargas', mbti: 'ISTJ', alias: 'La Logista',
    perfil: 'Metódica y confiable. Mantiene la red documentada, estandarizada y estable; prefiere cambios planificados con ventana de mantenimiento y plan de reversa.',
    fortalezas: ['Documentación y control de cambios rigurosos', 'Cumple SLA y procedimientos al detalle', 'Diagnóstico sistemático de fallas'],
    retos: ['Resistencia a cambios no planificados', 'Puede priorizar el proceso sobre la urgencia'],
    comunicacion: 'Envíale requerimientos por escrito, con datos y plazos concretos.',
    subtitulo: 'Operación y administración de la infraestructura de red', nivel: 'Nivel 3 · Operativo especializado', reportaA: 'Scrum Master / Coordinador de Redes', supervisa: [],
    funcionales: 'Coordina con Seguridad la aplicación de políticas y con Soporte la atención de incidentes. Colabora con Infraestructura y Desarrollo.',
    proposito: 'Diseñar, configurar y mantener la infraestructura de red cableada e inalámbrica, garantizando su disponibilidad, rendimiento y escalabilidad.',
    funciones: ['Diseñar la topología y la arquitectura de conectividad (LAN, WAN, VLAN, VPN).', 'Configurar enrutadores, conmutadores, cortafuegos y puntos de acceso.', 'Administrar DHCP, DNS, NAT, QoS y control de acceso.', 'Respaldar configuraciones y aplicar actualizaciones de firmware programadas.', 'Atender y escalar incidentes de conectividad de segundo nivel.', 'Gestionar la relación técnica con proveedores de enlaces e Internet.', 'Mantener el inventario de equipos y la documentación de red.'],
    responsabilidades: ['Operatividad continua de equipos y enlaces.', 'Custodia de credenciales y configuraciones de dispositivos.', 'Equipos, licencias y contratos de enlace asignados.', 'Aplicar cambios según el procedimiento de gestión de cambios.'],
    autoridad: ['Modificar configuraciones de red aprobadas en el plan de cambios.', 'Solicitar soporte técnico a proveedores.', 'Proponer compras de equipamiento.'],
    requisitos: ['Ingeniería en Sistemas, Redes, Telecomunicaciones o afines.', 'Mínimo 3 años administrando redes empresariales.', 'CCNA, JNCIA o equivalente (deseable).', 'Dominio de TCP/IP, OSPF, BGP, VLAN y VPN; scripting con Python o Ansible.'],
    competencias: ['Pensamiento lógico', 'Análisis de sistemas complejos', 'Resolución bajo presión', 'Disciplina documental', 'Trabajo colaborativo'],
    indicadores: [['Caídas de enlace no planificadas', '≤ 1 por trimestre'], ['Respaldos de configuración al día', '100 %'], ['Incidentes N2 resueltos en SLA', '≥ 90 %'], ['Documentación actualizada', 'Revisión mensual']],
    condiciones: ['Oficina, centro de datos y administración remota.', 'Ventanas de mantenimiento fuera del horario habitual.'],
    riesgos: ['Fatiga visual y postural.', 'Riesgo eléctrico y ergonómico en racks y gabinetes.'],
  },
  {
    clave: 'seguridad', codigo: 'TIC-RED-003', denominacion: 'Especialista en Seguridad de Redes', categoria: 'Profesional / Técnico especializado', color: 'pink', icon: '⛨',
    person: 'Javier Soto', mbti: 'INTJ', alias: 'El Arquitecto',
    perfil: 'Estratega analítico que piensa en escenarios de ataque antes de que ocurran. Diseña defensas en capas y cuestiona supuestos con argumentos técnicos.',
    fortalezas: ['Visión a largo plazo (Zero Trust, segmentación)', 'Análisis de riesgos y amenazas', 'Autonomía para investigar incidentes'],
    retos: ['Puede parecer distante o demasiado crítico', 'Poca paciencia con decisiones sin fundamento'],
    comunicacion: 'Ve directo al punto y trae evidencia; dale tiempo para analizar antes de decidir.',
    subtitulo: 'Protección, hardening y respuesta ante incidentes', nivel: 'Nivel 3 · Operativo especializado', reportaA: 'Scrum Master / Coordinador de Redes', supervisa: [],
    funcionales: 'Coordina con el Administrador la aplicación de controles y con Soporte la detección temprana. Colabora con Infraestructura, Desarrollo y auditoría interna.',
    proposito: 'Proteger la integridad, disponibilidad y confidencialidad de la información de la red, definiendo controles y respondiendo ante incidentes de seguridad.',
    funciones: ['Mantener políticas de cortafuegos, listas de acceso y segmentación segura.', 'Administrar IDS/IPS y filtrado de contenido.', 'Ejecutar análisis de vulnerabilidades y pruebas de penetración internas.', 'Endurecer (hardening) dispositivos y servicios expuestos.', 'Monitorear eventos de seguridad e investigar incidentes.', 'Coordinar la respuesta a incidentes y elaborar el informe forense.', 'Capacitar al personal en buenas prácticas de seguridad.'],
    responsabilidades: ['Controles de seguridad perimetral y de acceso.', 'Información sensible, credenciales privilegiadas y evidencia.', 'Confidencialidad de hallazgos de auditoría.', 'Decisiones de contención que pueden interrumpir un servicio.'],
    autoridad: ['Aislar equipos o bloquear tráfico ante un incidente activo.', 'Exigir remediación de vulnerabilidades críticas.', 'Auditar configuraciones de cualquier dispositivo de red.'],
    requisitos: ['Ingeniería en Sistemas, Informática, Redes o afines.', 'Mínimo 3 años en seguridad de redes.', 'Security+, CEH, CCNA Security o equivalente (deseable).', 'Conocimiento de ISO 27001, NIST, IDS/IPS, PKI y 802.1X.'],
    competencias: ['Pensamiento analítico', 'Ética y discreción', 'Respuesta ante crisis', 'Actualización permanente', 'Comunicación de riesgos'],
    indicadores: [['Tiempo medio de detección (MTTD)', '≤ 1 hora'], ['Vulnerabilidades críticas abiertas', '0 a más de 15 días'], ['Incidentes críticos', '0 por trimestre'], ['Personal capacitado', '100 % al año']],
    condiciones: ['Oficina con administración remota de plataformas.', 'Atención de incidentes críticos fuera de horario.'],
    riesgos: ['Estrés por incidentes con impacto reputacional.', 'Sobrecarga cognitiva por análisis continuo de alertas.'],
  },
  {
    clave: 'soporte', codigo: 'TIC-RED-004', denominacion: 'Soporte y Monitoreo de Redes', categoria: 'Técnico / Operativo', color: 'green', icon: '◷',
    person: 'Pablo Rojas', mbti: 'ISTP', alias: 'El Virtuoso',
    perfil: 'Práctico y sereno bajo presión. Brilla resolviendo incidentes en vivo, con las manos en el equipo y la consola, adaptándose rápido a lo inesperado.',
    fortalezas: ['Respuesta rápida ante caídas', 'Resolución práctica en sitio', 'Calma en situaciones críticas'],
    retos: ['Tiende a postergar reportes y documentación', 'Se desmotiva con tareas repetitivas'],
    comunicacion: 'Sé breve y concreto; muéstrale el problema real en lugar de explicarlo en abstracto.',
    subtitulo: 'Vigilancia continua y atención de incidentes de conectividad', nivel: 'Nivel 3 · Operativo', reportaA: 'Scrum Master / Coordinador de Redes', supervisa: [],
    funcionales: 'Escala al Administrador de Redes y al Especialista en Seguridad. Atiende a usuarios internos de todas las áreas.',
    proposito: 'Vigilar de forma continua el estado de la red y atender en primera línea los incidentes de conectividad, escalando oportunamente lo que exceda su nivel.',
    funciones: ['Operar plataformas de monitoreo y configurar alertas, umbrales y tableros.', 'Recibir, clasificar y atender tickets de soporte de red.', 'Ejecutar diagnósticos de primer nivel con soluciones documentadas.', 'Escalar al Administrador o a Seguridad los casos que exceden su nivel.', 'Elaborar reportes periódicos de disponibilidad, tráfico e incidentes.', 'Verificar el estado físico de equipos, gabinetes y cableado.', 'Mantener la base de conocimiento y los procedimientos operativos.'],
    responsabilidades: ['Vigilancia permanente y notificación oportuna de eventos.', 'Registro fiel y completo de incidentes.', 'Confidencialidad de los datos accedidos durante el soporte.', 'Cuidado del instrumental de diagnóstico asignado.'],
    autoridad: ['Abrir, priorizar y escalar tickets.', 'Reiniciar servicios según procedimientos documentados.', 'Solicitar acceso a áreas técnicas para inspección.'],
    requisitos: ['Técnico superior o estudios universitarios en Sistemas, Redes o afines.', '1 a 2 años en soporte técnico o mesa de ayuda.', 'Fundamentos de TCP/IP, DNS, DHCP, cableado y Wi-Fi.', 'Manejo de Zabbix, PRTG, Nagios o Grafana y sistemas de tickets.'],
    competencias: ['Atención al detalle', 'Orientación al servicio', 'Comunicación clara', 'Método y organización', 'Proactividad'],
    indicadores: [['Tickets N1 resueltos en SLA', '≥ 90 %'], ['Activos de red monitoreados', '100 %'], ['Tiempo de primera respuesta', '≤ 15 min'], ['Satisfacción del usuario', '≥ 4.5 / 5']],
    condiciones: ['Oficina y sala de monitoreo; visitas a puestos de usuario.', 'Posibles turnos o guardias.'],
    riesgos: ['Fatiga visual por vigilancia continua de pantallas.', 'Estrés por múltiples incidentes en horas pico.'],
  },
]

export const POSITIONS = [
  {
    id: 'ceo', title: 'Directora General', area: 'Dirección', reportsTo: null, person: 'Laura Méndez', photo: '1494790108377-be9c29b29330', mbti: 'ENTJ', color: 'yellow',
    summary: 'Define la estrategia de IATECH, representa a la empresa y asegura el crecimiento sostenible.',
    duties: ['Fijar la estrategia y los objetivos anuales', 'Aprobar presupuestos e inversiones', 'Relación con socios y clientes clave'],
    reqs: ['10+ años liderando empresas de tecnología', 'MBA o afín', 'Visión de negocio en telecomunicaciones'],
    goals: [['Crecer 25% en facturación', 62], ['Abrir 2 nuevas regiones', 50]],
  },
  {
    id: 'cto', title: 'Gerente de Tecnología y Redes', area: 'Redes', reportsTo: 'ceo', person: 'Carlos Ríos', photo: '1507003211169-0a1dd7228f2d', mbti: 'INTJ', color: 'blue',
    summary: 'Lidera el área de redes: arquitectura, operación, seguridad y hoja de ruta tecnológica.',
    duties: ['Definir la hoja de ruta tecnológica', 'Supervisar proyectos de infraestructura', 'Garantizar SLA de disponibilidad'],
    reqs: ['Ing. en Telecomunicaciones o Sistemas', 'CCNP / CCIE deseable', '7+ años en redes empresariales'],
    goals: [['Disponibilidad de red 99.95%', 80], ['Migrar 60% de clientes a SD-WAN', 45]],
  },
  {
    id: 'cfo', title: 'Gerente de Administración y Finanzas', area: 'Administración', reportsTo: 'ceo', person: 'Ana Torres', photo: '1438761681033-6461ffad8d80', mbti: 'ESTJ', color: 'green',
    summary: 'Gestiona finanzas, compras, contratos y talento humano de la empresa.',
    duties: ['Control presupuestario y flujo de caja', 'Compras de equipamiento', 'Gestión de personal y nómina'],
    reqs: ['Lic. en Finanzas o Contabilidad', '5+ años en cargos similares'],
    goals: [['Reducir costos operativos 10%', 70], ['Cierre contable en 5 días', 90]],
  },
  {
    id: 'com', title: 'Gerente Comercial', area: 'Comercial', reportsTo: 'ceo', person: 'Diego Paz', photo: '1500648767791-00dcc994a43e', mbti: 'ENFJ', color: 'pink',
    summary: 'Impulsa las ventas de soluciones de conectividad y la relación con clientes.',
    duties: ['Plan comercial y metas de venta', 'Preventa junto al área técnica', 'Fidelización de clientes'],
    reqs: ['Experiencia en venta consultiva B2B', 'Conocimiento de soluciones TIC'],
    goals: [['30 nuevos clientes corporativos', 55], ['NPS mayor a 60', 75]],
  },
  {
    id: 'arq', title: 'Arquitecta de Redes', area: 'Redes', reportsTo: 'cto', person: 'Sofía Vargas', photo: '1573164713714-d95e436ab8d6', mbti: 'INTP', color: 'lilac',
    summary: 'Diseña redes LAN, WAN, Wi-Fi y data center escalables y seguras.',
    duties: ['Diseño de topologías y direccionamiento', 'Evaluar nuevas tecnologías', 'Documentación técnica'],
    reqs: ['CCNP Enterprise', 'Experiencia en SD-WAN y Wi-Fi 6/7'],
    goals: [['Plantilla estándar SD-WAN', 65], ['Certificación CCIE (escrito)', 40]],
  },
  {
    id: 'sec', title: 'Especialista en Ciberseguridad', area: 'Redes', reportsTo: 'cto', person: 'Javier Soto', photo: '1535713875002-d1d0cf377fde', mbti: 'ISTJ', color: 'peach',
    summary: 'Protege la infraestructura: firewalls, Zero Trust, monitoreo de amenazas y respuesta a incidentes.',
    duties: ['Políticas de firewall y segmentación', 'Gestión de vulnerabilidades', 'Respuesta a incidentes'],
    reqs: ['Security+ / CISSP', 'Experiencia con NGFW y SIEM'],
    goals: [['0 incidentes críticos', 85], ['Implementar Zero Trust interno', 35]],
  },
  {
    id: 'noc', title: 'Coordinadora NOC', area: 'Redes', reportsTo: 'cto', person: 'Mariana Cruz', photo: '1580489944761-15a19d654956', mbti: 'ISTP', color: 'green',
    summary: 'Coordina el centro de operaciones de red 24/7 y la atención de incidentes.',
    duties: ['Turnos y guardias del NOC', 'Monitoreo y escalamiento', 'Reportes de SLA'],
    reqs: ['CCNA', 'ITIL Foundation', 'Experiencia en herramientas de monitoreo'],
    goals: [['MTTR menor a 2 h', 72], ['Automatizar 50% de alertas', 48]],
  },
  {
    id: 'sm', title: 'Scrum Master / PMO', area: 'Redes', reportsTo: 'cto', person: 'Andrés León', mbti: 'ENFP', color: 'yellow',
    summary: 'Facilita Scrum en los proyectos de red y elimina impedimentos del equipo.',
    duties: ['Facilitar eventos Scrum', 'Mantener el tablero Kanban', 'Métricas de entrega'],
    reqs: ['PSM I o CSM', 'Experiencia en proyectos de infraestructura'],
    goals: [['Velocidad estable ±10%', 68], ['100% retros con acciones', 90]],
  },
  {
    id: 'tec', title: 'Técnico de Soporte e Instalaciones', area: 'Redes', reportsTo: 'noc', person: 'Pablo Rojas', mbti: 'ISFJ', color: 'blue',
    summary: 'Instala, configura y da soporte en sitio a equipos de red de clientes.',
    duties: ['Instalación de cableado y equipos', 'Soporte de primer y segundo nivel', 'Mantenimiento preventivo'],
    reqs: ['Técnico en redes', 'CCNA deseable', 'Licencia de conducir'],
    goals: [['Aprobar CCNA', 60], ['95% de visitas resueltas', 82]],
  },
  {
    id: 'cont', title: 'Contadora', area: 'Administración', reportsTo: 'cfo', person: 'Elena Gil', mbti: 'ISTJ', color: 'green',
    summary: 'Registra operaciones contables y cumple obligaciones tributarias.',
    duties: ['Estados financieros', 'Impuestos y declaraciones', 'Conciliaciones'],
    reqs: ['Contadora titulada', '3+ años de experiencia'],
    goals: [['Digitalizar 100% de facturas', 88]],
  },
  {
    id: 'ven', title: 'Ejecutiva de Cuentas', area: 'Comercial', reportsTo: 'com', person: 'Lucía Ortiz', mbti: 'ESFP', color: 'pink',
    summary: 'Gestiona la cartera de clientes y detecta nuevas oportunidades.',
    duties: ['Prospección y visitas', 'Propuestas comerciales', 'Seguimiento postventa'],
    reqs: ['Experiencia en ventas TIC', 'Excelente comunicación'],
    goals: [['Cuota trimestral de ventas', 58]],
  },
]

export const VIDEOS = [
  { id: 'keeqnciDVOo', title: 'Redes de computadoras en 100 segundos', tag: 'Fundamentos' },
  { id: '3QhU9jd03a0', title: 'Computer Networks — Crash Course', tag: 'Historia' },
  { id: 'AEaKrq3SpW8', title: 'Cómo funciona Internet — Crash Course', tag: 'Internet' },
  { id: '_IOZ8_cPgu8', title: 'Switch, router, subred, firewall y DMZ', tag: 'Infraestructura' },
  { id: 'vv4y_uOneC0', title: 'Modelo OSI animado', tag: 'Protocolos' },
]
